import type { MediaId } from "@canto/core/domain/media/types/media";

/** Branded id for the `media_credit` table primary key. */
export type MediaCreditId = string & { readonly __brand: "MediaCreditId" };

/** Discriminator: cast appears on screen, crew works behind the scenes. */
export type CreditType = "cast" | "crew";

/**
 * Domain entity for a `media_credit` row. Mirrors the schema 1:1; cast rows
 * carry `character`, crew rows carry `department` + `job`. The same person can
 * appear multiple times for different roles (handled at the row level — there
 * is no per-(media, person) uniqueness).
 */
export interface MediaCredit {
  id: MediaCreditId;
  mediaId: MediaId;
  /** TMDB person id — kept as a numeric foreign key, even though we don't
   *  yet maintain a local `person` table. */
  personId: number;
  name: string;
  character: string | null;
  department: string | null;
  job: string | null;
  profilePath: string | null;
  type: CreditType;
  /** Display order within the cast/crew list. Adapter ensures this is
   *  populated even when the provider payload omits it (falls back to the
   *  array index). */
  order: number;
}

/** Insert input. `id` is generated by the database. */
export interface NewMediaCredit {
  mediaId: MediaId | string;
  personId: number;
  name: string;
  character?: string | null;
  department?: string | null;
  job?: string | null;
  profilePath?: string | null;
  type: CreditType;
  order: number;
}
