import type { MediaId } from "@canto/core/domain/media/types/media";

/** Branded id for the `media_content_rating` table primary key. */
export type MediaContentRatingId = string & {
  readonly __brand: "MediaContentRatingId";
};

/**
 * Domain entity for a `media_content_rating` row. One row per (media, region)
 * tuple — region uniqueness is enforced via the `idx_media_content_rating_unique`
 * index. Pure storage: no timestamps, no source metadata.
 */
export interface MediaContentRating {
  id: MediaContentRatingId;
  mediaId: MediaId;
  region: string;
  rating: string;
}

/** Insert input. `id` is generated by the database. */
export interface NewMediaContentRating {
  mediaId: MediaId | string;
  region: string;
  rating: string;
}
