import type { MediaId } from "@canto/core/domain/media/types/media";

/** Branded id for the `media_watch_provider` table primary key. */
export type MediaWatchProviderId = string & {
  readonly __brand: "MediaWatchProviderId";
};

/** "stream" = subscription, "rent" / "buy" = transactional. */
export type WatchProviderType = "stream" | "rent" | "buy" | string;

/**
 * Domain entity for a `media_watch_provider` row. One row per
 * `(mediaId, providerId, type, region)` — the same provider can list a media
 * under multiple offer types (e.g. Netflix flatrate in BR + buy in US).
 */
export interface MediaWatchProvider {
  id: MediaWatchProviderId;
  mediaId: MediaId;
  /** TMDB watch-provider id (e.g. 8 = Netflix). */
  providerId: number;
  providerName: string;
  logoPath: string | null;
  type: WatchProviderType;
  /** ISO 3166-1 alpha-2 region code (`BR`, `US`, …). */
  region: string;
}

/** Insert input. `id` is generated by the database. */
export interface NewMediaWatchProvider {
  mediaId: MediaId | string;
  providerId: number;
  providerName: string;
  logoPath?: string | null;
  type: WatchProviderType;
  region: string;
}

/**
 * Row shape from `watch_provider_link` — TMDB-global mapping of providerId →
 * search-URL template (used by the "where to watch" deeplink rendering).
 */
export interface WatchProviderLink {
  providerId: number;
  searchUrlTemplate: string | null;
}
