import type { MediaId } from "@canto/core/domain/media/types/media";

/** Branded id for the `media_video` table primary key. */
export type MediaVideoId = string & { readonly __brand: "MediaVideoId" };

/**
 * Domain entity for a `media_video` row — trailers, teasers, clips, behind-
 * the-scenes. The provider key (`externalKey`) is the YouTube video id when
 * `site === "YouTube"` and the corresponding identifier on other sites.
 */
export interface MediaVideo {
  id: MediaVideoId;
  mediaId: MediaId;
  /** Site-specific provider key — e.g. YouTube video id. */
  externalKey: string;
  site: string;
  name: string;
  /** Trailer / Teaser / Clip / Featurette / Behind the Scenes / Bloopers */
  type: string;
  official: boolean;
  /** TMDB iso_639_1 tag (`en`, `pt`, …). `null` when the provider didn't
   *  surface a language. */
  language: string | null;
  publishedAt: Date | null;
}

/** Insert input. `id` is generated by the database. */
export interface NewMediaVideo {
  mediaId: MediaId | string;
  externalKey: string;
  site: string;
  name: string;
  type: string;
  official?: boolean;
  language?: string | null;
  publishedAt?: Date | null;
}
